name: Process MP3 and Return Base64

on:
  workflow_dispatch:  # This will allow the workflow to be triggered manually via the API

jobs:
  run_demucs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and process audio
        env:
          AUDIO_URL: ${{ github.event.inputs.audio_url }}
        run: |
          python run_demucs.py

      - name: Encode processed audio to Base64
        run: |
          python encode_to_base64.py

      - name: Return Base64 Data
        id: return_base64
        run: |
          cat /tmp/processed_audio_base64.txt
        outputs:
          base64_audio: ${{ steps.return_base64.outputs.result }}
