name: Run Demucs

on:
  push:
    branches:
      - main

jobs:
  run_demucs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and process audio
        env:
          AUDIO_URL: 'https://raw.githubusercontent.com/designBazar/designBazar.github.io/main/CHAND_MAMA_%E0%A6%9A%E0%A6%BE%E0%A6%81%E0%A6%A6_%E0%A6%AE%E0%A6%BE%E0%A6%AE%E0%A6%BE_%EF%BD%9C_VIDEO_SONG_%EF%BD%9C_BORBAAD_%EF%BD%9C_SHAKIB_KHAN_%EF%BD%9CNUSRAT.mp3'
        run: |
          python run_demucs.py

      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: demucs-output
          path: output/  # This directory now contains the output files
