name: Demucs Audio Separation

on:
  workflow_dispatch:
    inputs:
      audio_url:
        description: 'Direct link to MP3 file'
        required: true

jobs:
  separate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.0

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Demucs
        run: python run_demucs.py
        env:
          AUDIO_URL: ${{ github.event.inputs.audio_url }}
