name: Spleeter Base64 API

on:
  workflow_dispatch:
    inputs:
      audio_url:
        description: 'MP3 URL'
        required: true

jobs:
  spleeter_job:
    runs-on: ubuntu-latest
    outputs:
      base64_json: ${{ steps.encode.outputs.base64_json }}

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install spleeter==2.4.0

    - name: Download audio
      run: |
        mkdir -p input_audio
        wget "${{ github.event.inputs.audio_url }}" -O input_audio/input.mp3 || { echo "Error: Failed to download audio file"; exit 1; }
        ls -lh input_audio/
        file input_audio/input.mp3

    - name: Run Spleeter
      id: spleeter
      run: |
        if [ -f "input_audio/input.mp3" ]; then
          echo "Running Spleeter separation..."
          spleeter separate -i "input_audio/input.mp3" -o output
          ls -lh output/
          ls -lh output/input/
        else
          echo "Error: input_audio/input.mp3 does not exist"
          exit 1
        fi

    - name: Convert to Base64 and create JSON
      id: encode
      run: |
        if [ -f "output/input/vocals.wav" ] && [ -f "output/input/accompaniment.wav" ]; then
          vocals_base64=$(base64 -w 0 "output/input/vocals.wav")
          accompaniment_base64=$(base64 -w 0 "output/input/accompaniment.wav")
          echo "Vocals Base64 length: ${#vocals_base64}"
          
          if [ ${#vocals_base64} -gt 1000000 ]; then
            echo "Base64 data too large, saving as artifact."
            echo "$vocals_base64" > vocals_base64.txt
            echo "$accompaniment_base64" > accompaniment_base64.txt
          else
            json="{\"vocals\":\"$vocals_base64\",\"accompaniment\":\"$accompaniment_base64\"}"
            echo "base64_json=$json" >> $GITHUB_OUTPUT
          fi
        else
          echo "Error: Output files missing"
          exit 1
        fi

    - name: Upload Base64 as Artifact (if large)
      if: steps.encode.outputs.base64_json == ''
      uses: actions/upload-artifact@v4
      with:
        name: base64_audio_files
        path: |
          vocals_base64.txt
          accompaniment_base64.txt
