name: Run Demucs

on:
  workflow_dispatch:
    inputs:
      audio_url:
        description: 'URL of the audio to process'
        required: true

jobs:
  run_demucs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10.0  # Use a supported version of Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.0 # Updated Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and process audio
        run: |
          python run_demucs.py
        env:
          AUDIO_URL: ${{ github.event.inputs.audio_url }}

      - name: Base64 encode the output audio
        run: |
          python encode_to_base64.py /tmp/output_audio.wav
        id: encode_audio

      - name: Return the base64 encoded audio
        run: |
          echo "Base64 encoded audio: ${{ steps.encode_audio.outputs.base64_audio }}"
