name: Demucs Separator

on:
  workflow_dispatch:
    inputs:
      audio_url:
        description: 'URL to the MP3 file'
        required: true

jobs:
  separate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Demucs separation
        run: python run_demucs.py
        env:
          AUDIO_URL: ${{ github.event.inputs.audio_url }}

      - name: Upload results
        uses: actions/upload-artifact@v2 # This should still work
        with:
          name: demucs_output
          path: output.json
