name: Run Demucs

on:
  workflow_dispatch:
    inputs:
      audio_url:
        description: 'URL of the audio to process'
        required: true

jobs:
  run_demucs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ffmpeg and ffprobe
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download and process audio
        run: |
          python run_demucs.py
        env:
          AUDIO_URL: ${{ github.event.inputs.audio_url }}

      - name: Check if output exists
        run: |
          if [ -f /tmp/output.json ]; then
            echo "Output file exists, proceeding with upload."
          else
            echo "Output file not found!"
            exit 1
          fi

      - name: Upload output artifact
        uses: actions/upload-artifact@v3
        with:
          name: demucs-output
          path: /tmp/output.json
