name: Demucs Separator

on:
  workflow_dispatch:
    inputs:
      audio_url:
        description: 'Audio URL (YouTube or direct MP3)'
        required: true

jobs:
  separate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install torch torchaudio demucs==4.0.1 yt-dlp

      - name: Run Demucs separation
        run: python run_demucs.py
        env:
          AUDIO_URL: ${{ github.event.inputs.audio_url }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: demucs_output
          path: output.json
